### ISSUE TITLE
SVM chapter related questions

### ISSUE THREAD

**Issue by abc744587** [GAR-Project/project#11]
Dear all,

The first question is,should `data_gathering.py` be executed locally on Windows? Or should it be in the VM?
Because I don't see `data_gathering.py` in both VMs.

![image](https://user-images.githubusercontent.com/85470040/194261160-4314362d-6c1c-4c77-8c06-bd31f4400d5f.png)

==================================================================================
The second question is, does matplotlib have to perform extra?
![image](https://user-images.githubusercontent.com/85470040/194262358-5308bf01-6b0c-48f7-98b3-d1034e2bbefc.png)

Thank you all for listening.
--Ren

**Comment by davidcawork** [comment]
Hello @abc744587 !

Let's go by parts,


First of all, the whole project is designed to run in a Linux environment! So I don't understand why you are asking if it should run in Windows or in a VM. I strongly recommend you to read section [Installation methods](https://github.com/GAR-Project/project#installation-methods-wrench) again.

Second, the `data_gathering.py` script only serves to generate the datasets that you can find here. We have also added it so as not to take anything for granted and to be completely transparent with the reader.


Third,  


> The second question is, does matplotlib have to perform extra?


I don't understand the question, what do you mean? Feel free to rephrase the question and reopen the issue if u want

Have a nice day!

**Comment by abc744587** [comment]
Dear @davidcawork ,

Do you mean the whole environment will be executed in Vagrant in Linux?
Because I use Vagrant in Windows to start test&controller.

And I don't see `data_gathering.py` in the `test` and `controller` machine. It can only be seen in the project downloaded by clone.

> The second question is, does matplotlib have to perform extra?

Sorry, I mean does matplotlib need to be installed extra?

Thank you all for listening.
--Ren

**Comment by davidcawork** [comment]
Hi,

What I mean is, the test and control environment is going to be Linux machines. The fact that you use Vagrant to run two Linux virtual machines does not imply that you run the scritps from Windows, that's what I meant. The `data_gathering.py` file is not on any of the machines because it has been used in parallel to generate the dataset.

You don't need matplotlib to run the tests. If you want to paint the results with matplotlib as we have done, you can do it.

**Comment by abc744587** [comment]
Dear @davidcawork ,

Thanks for your answer :smiley: .

If I have other questions, I will ask you again. 

--Ren

**Comment by davidcawork** [comment]
It will be our pleasure to help!
