### ISSUE TITLE
install graphana and import controller - mininet

### ISSUE THREAD

**Issue by viettd14** [GAR-Project/project#17]
Dear,
in util folder you mentioned ansible section to install graphana and copy_files.sh.
Can you guide how to do it?

**Comment by davidcawork** [comment]
Hello @viettd14 ,

I'm sorry, but we dont have any Ansible section. Please, clarify what you meant, because I don't understand you.

If you want to install grafana, just use the shell script like this:

```bash
# You have to give the script execution permissions 
chmod +x ./util/install_grafana_influxdb.sh

# Then, just run it
./util/install_grafana_influxdb.sh
```
