### ISSUE TITLE
Controller_VM ryu-manager error

### ISSUE THREAD

**Issue by abc744587** [GAR-Project/project#6]
Hello everyone,
When I enter ryu-manager ryu.app.simple_switch_13 in Controller_VM, I get the following error.

/
vagrant@controller:~/project$ ryu-manager ryu.app.simple_switch_13
Traceback (most recent call last):
  File "/usr/local/bin/ryu-manager", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3088, in <module>
    @_call_aside
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3072, in _call_aside
    f(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 3101, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 574, in _build_master
    ws.require(__requires__)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 892, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 778, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'webob>=1.2' distribution was not found and is required by ryu
/

I also installed webob, but the result is still the same....

Thanks everyone.

**Comment by pcolladosoto** [comment]
Hi @abc744587! Let's see if we can sort this out to get you back up and running in no time 😜.

First things first: what command did you install `webob` with?

**Comment by abc744587** [comment]
Hi @pcolladosoto, I used "pip install WebOb" and "pip3 install WebOb" to install WebOb, but the error is still displayed, and I installed it on the Controller_VM of the Project.

**Comment by pcolladosoto** [comment]
Hi @abc744587! Just an update: we've managed to get stuff working again!

We have decided to update the VM image all the way up to Ubuntu 20.04: Ubuntu 16.04 was too far behind to make fixing stuff feasible...

We'll try to bundle all the tweaks up in a PR and merge it to `master` before the end of the week.

We'll let you know when that's done and we'll wait for you to confirm everything is working on your end.

**Comment by abc744587** [comment]
Ok!Thanks @pcolladosoto ！

**Comment by pcolladosoto** [comment]
Hi @abc744587! The PR I just merged should fix the issue. You will need to destroy your VMs with `vagrant destroy` and then recreate the entire thing with `vagrant up` after pulling the latest changes.

Feel free to reopen the issue if you encounter any problems!

Hope you find our work useful 😼
